-- ==== Projeto DBDeliveryPharma === --
-- ====   Hélio  Marques  === --

-- ==== Criação das tables e indexes === --
-- --------------------------------------- --

-- Drop das tabelas (se existirem)
--DROP TABLE ItensPedido;
--DROP TABLE PedidosEntrega;
--DROP TABLE Pedidos;
--DROP TABLE Clientes;
--DROP TABLE TipoProduto;
--DROP TABLE Entregador;
--DROP TABLE OrdemEntrega;
--DROP TABLE Produtos;

-- Criação da tabela Clientes
CREATE TABLE Clientes (
  CodigoClientes INTEGER NOT NULL PRIMARY KEY,
  CNPJClientes VARCHAR(14),
  NomeClientes VARCHAR(80),
  CEPClientes VARCHAR(8),
  RuaClientes VARCHAR(100),
  BairroClientes VARCHAR(50),
  CidadeClientes VARCHAR(50),
  UFClientes VARCHAR(2),
  LongitudeClientes DECIMAL(17,7),
  LatitudeClientes DECIMAL(17,7),
  CodIBGEClientes VARCHAR(10),
  NomeFantasiaClientes VARCHAR(100),
  SitCadastralClientes VARCHAR(30),
  NumeroRuaClientes INTEGER
);
CREATE GENERATOR GEN_Clientes_ID;
COMMIT;

CREATE INDEX INDEX_NOME ON Clientes (NomeClientes);
COMMIT;

-- Criação da tabela TipoProduto
CREATE TABLE TipoProduto (
  idTipoProduto INTEGER NOT NULL PRIMARY KEY,
  DescricaoTipoProduto VARCHAR(50),
  PrioridadeTipoProduto SMALLINT DEFAULT 0,
  PrescricaoTipoProduto SMALLINT DEFAULT 0,
  CuidadosTipoProduto SMALLINT DEFAULT 0,
  DataValidadeTipoProduto SMALLINT DEFAULT 0
);
CREATE GENERATOR GEN_TipoProduto_ID;
COMMIT;

-- Criação da tabela Produtos 
CREATE TABLE Produtos (
  idProdutos INTEGER NOT NULL PRIMARY KEY,
  TipoProdutoProdutos INTEGER NOT NULL,
  CodigoProdutos VARCHAR(10),
  DescricaoProdutos VARCHAR(80),
  PrecoVendaProdutos DECIMAL(17,3),
  PrescricaoProdutos VARCHAR(1000),
  CuidadosArmProdutos VARCHAR(1000),
  DataValidadeProdutos DATE,
  CONSTRAINT FK_TipoProduto FOREIGN KEY (TipoProdutoProdutos)
    REFERENCES TipoProduto (idTipoProduto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE GENERATOR GEN_Produtos_ID;
COMMIT;

CREATE INDEX INDEX_DESCRICAO ON Produtos (DescricaoProdutos);
CREATE INDEX FK_TIPOPRODUTO_idx ON Produtos (TipoProdutoProdutos);
COMMIT;

-- Criação da tabela Pedidos
CREATE TABLE Pedidos (
  NumeroPedidos INTEGER NOT NULL PRIMARY KEY,
  DataEmissaoPedidos TIMESTAMP,
  ClientePedidos INTEGER,
  ValorTotalPedidos DECIMAL(17,3),
  CONSTRAINT FK_CLIENTE FOREIGN KEY (ClientePedidos)
    REFERENCES Clientes (CodigoClientes)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE GENERATOR GEN_Pedidos_ID;
COMMIT;

CREATE INDEX FK_CLIENTE_idx ON Pedidos (ClientePedidos);
CREATE INDEX INDEX_DATAEMISSAO ON Pedidos (DataEmissaoPedidos);
COMMIT;

-- Criação da tabela ItensPedido
CREATE TABLE ItensPedido (
  idItensPedido INTEGER NOT NULL PRIMARY KEY,
  PedidoItensPedido INTEGER,
  ProdutoItensPedido INTEGER,
  QuantidadeItensPedido DECIMAL(10,2),
  VlrUnitarioItensPedido DECIMAL(17,3),
  VlrTotalItensPedido DECIMAL(17,3),
  CONSTRAINT FK_PEDIDO FOREIGN KEY (PedidoItensPedido)
    REFERENCES Pedidos (NumeroPedidos)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT FK_PRODUTO FOREIGN KEY (ProdutoItensPedido)
    REFERENCES Produtos (idProdutos)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);
CREATE GENERATOR GEN_ItensPedido_ID;
COMMIT;

CREATE INDEX FK_PEDIDO_idx ON ItensPedido (PedidoItensPedido);
CREATE INDEX FK_PRODUTO_idx ON ItensPedido (ProdutoItensPedido);
COMMIT;

-- Criação da tabela Entregador
CREATE TABLE Entregador (
  idEntregador INTEGER NOT NULL PRIMARY KEY,
  NomeEntregador VARCHAR(50),
  SituacaoEntregador SMALLINT DEFAULT 0
);
CREATE GENERATOR GEN_Entregador_ID;
COMMIT;

-- Criação da tabela OrdemEntrega
CREATE TABLE OrdemEntrega (
  idOrdemEntrega INTEGER NOT NULL PRIMARY KEY,
  EntregadorOrdenEntrega INTEGER NOT NULL,
  EmissaoOrdemEntrega TIMESTAMP,
  SaidaOrdemEntrega TIMESTAMP,
  ChegadaOrdemEntrega TIMESTAMP,
  StatusOrdemEntrega SMALLINT DEFAULT 0,
  OBSOrdemEntrega VARCHAR(1000),
  CONSTRAINT fk_OrdemEntrega_Entregador FOREIGN KEY (EntregadorOrdenEntrega)
    REFERENCES Entregador (idEntregador)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE GENERATOR GEN_OrdemEntrega_ID;
COMMIT;

CREATE INDEX FK_ENTREGADORORDEMENTREGA_idx ON OrdemEntrega (EntregadorOrdenEntrega);
COMMIT;

-- Criação da tabela PedidosEntrega
CREATE TABLE PedidosEntrega (
  idPedidosEntrega INTEGER NOT NULL PRIMARY KEY,
  PedidoPedidosEntrega INTEGER NOT NULL,
  OrdemEntregaPedidosEntrega INTEGER NOT NULL,
  StatusPedidosEntrega SMALLINT DEFAULT 0,
  OBSPedidosEntrega VARCHAR(1000),
  CONSTRAINT fk_PedidosEntrega_Pedidos FOREIGN KEY (PedidoPedidosEntrega)
    REFERENCES Pedidos (NumeroPedidos)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PedidosEntrega_OrdemEntrega FOREIGN KEY (OrdemEntregaPedidosEntrega)
    REFERENCES OrdemEntrega (idOrdemEntrega)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE GENERATOR GEN_PedidosEntrega_ID;
COMMIT;

CREATE INDEX FK_PEDIDOS_idx ON PedidosEntrega (PedidoPedidosEntrega);
CREATE INDEX FK_ORDEMENTREGA_idx ON PedidosEntrega (OrdemEntregaPedidosEntrega);
COMMIT;


CONNECT 'C:\DeliveryPharma\BD\dbDeliveryPharma.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

-- Clientes
INSERT INTO CLIENTES (CODIGOCLIENTES, CNPJCLIENTES, NOMECLIENTES, CEPCLIENTES, RUACLIENTES, BAIRROCLIENTES, CIDADECLIENTES, UFCLIENTES, LONGITUDECLIENTES, LATITUDECLIENTES, CODIBGECLIENTES, NOMEFANTASIACLIENTES, SITCADASTRALCLIENTES, NUMERORUACLIENTES)
VALUES (GEN_ID(GEN_Clientes_ID, 1), '14796606000190', 'ADYEN DO BRASIL INSTITUICAO DE PAGAMENTO LTDA.', '60744325', 'Rua Shirley Girao', 'Passare', 'Fortaleza', 'CE', 0, 0, '2304400', 'ADYEN LATIN AMERICA', 'ATIVA', 571);
INSERT INTO CLIENTES (CODIGOCLIENTES, CNPJCLIENTES, NOMECLIENTES, CEPCLIENTES, RUACLIENTES, BAIRROCLIENTES, CIDADECLIENTES, UFCLIENTES, LONGITUDECLIENTES, LATITUDECLIENTES, CODIBGECLIENTES, NOMEFANTASIACLIENTES, SITCADASTRALCLIENTES, NUMERORUACLIENTES)
VALUES (GEN_ID(GEN_Clientes_ID, 1), '12345678000195', 'ROBERIO JOSE DOS SANTOS 16952477870', '60744320', 'Rua 4', 'Passare', 'Fortaleza', 'CE', 0, 0, '2304400', '', 'BAIXADA', 20);
INSERT INTO CLIENTES (CODIGOCLIENTES, CNPJCLIENTES, NOMECLIENTES, CEPCLIENTES, RUACLIENTES, BAIRROCLIENTES, CIDADECLIENTES, UFCLIENTES, LONGITUDECLIENTES, LATITUDECLIENTES, CODIBGECLIENTES, NOMEFANTASIACLIENTES, SITCADASTRALCLIENTES, NUMERORUACLIENTES)
VALUES (GEN_ID(GEN_Clientes_ID, 1), '09346601000125', 'B3 S.A. - BRASIL, BOLSA, BALCAO', '60744330', 'Rua 5', 'Passare', 'Fortaleza', 'CE', 0, 0, '2304400', 'B3 S.A. BRASIL, BOLSA, BALCAO', 'ATIVA', 2);


-- Tipo de Produto
INSERT INTO TIPOPRODUTO (IDTIPOPRODUTO, DESCRICAOTIPOPRODUTO, PRIORIDADETIPOPRODUTO, PRESCRICAOTIPOPRODUTO, CUIDADOSTIPOPRODUTO, DATAVALIDADETIPOPRODUTO)
VALUES (GEN_ID(GEN_TipoProduto_ID, 1), 'MEDICAMENTOS SENSIVEIS', 1, 1, 1, 1);
INSERT INTO TIPOPRODUTO (IDTIPOPRODUTO, DESCRICAOTIPOPRODUTO, PRIORIDADETIPOPRODUTO, PRESCRICAOTIPOPRODUTO, CUIDADOSTIPOPRODUTO, DATAVALIDADETIPOPRODUTO)
VALUES (GEN_ID(GEN_TipoProduto_ID, 1), 'MEDICAMENTOS CONTROLADOS', 2, 1, 1, 1);
INSERT INTO TIPOPRODUTO (IDTIPOPRODUTO, DESCRICAOTIPOPRODUTO, PRIORIDADETIPOPRODUTO, PRESCRICAOTIPOPRODUTO, CUIDADOSTIPOPRODUTO, DATAVALIDADETIPOPRODUTO)
VALUES (GEN_ID(GEN_TipoProduto_ID, 1), 'MEDICAMENTOS COMUNS', 9, 0, 0, 1);
INSERT INTO TIPOPRODUTO (IDTIPOPRODUTO, DESCRICAOTIPOPRODUTO, PRIORIDADETIPOPRODUTO, PRESCRICAOTIPOPRODUTO, CUIDADOSTIPOPRODUTO, DATAVALIDADETIPOPRODUTO)
VALUES (GEN_ID(GEN_TipoProduto_ID, 1), 'COSMETICOS', 9, 0, 0, 1);
INSERT INTO TIPOPRODUTO (IDTIPOPRODUTO, DESCRICAOTIPOPRODUTO, PRIORIDADETIPOPRODUTO, PRESCRICAOTIPOPRODUTO, CUIDADOSTIPOPRODUTO, DATAVALIDADETIPOPRODUTO)
VALUES (GEN_ID(GEN_TipoProduto_ID, 1), 'PRODUTOS GERAIS', 9, 0, 0, 0);
INSERT INTO TIPOPRODUTO (IDTIPOPRODUTO, DESCRICAOTIPOPRODUTO, PRIORIDADETIPOPRODUTO, PRESCRICAOTIPOPRODUTO, CUIDADOSTIPOPRODUTO, DATAVALIDADETIPOPRODUTO)
VALUES (GEN_ID(GEN_TipoProduto_ID, 1), 'PRODUTOS GERAIS PERECIVEIS', 9, 0, 0, 1);

-- Confirma as alterações
COMMIT;
